package com.zhibodata.gis.kfqpopulation;



public interface Codes {


     enum  KEYPOPULATION{
         ELDERLYPOPUTION, DISABLEPOPUTION,DBPOPUTION,WBPOPULATION,DBBYPOPUTION,
         ELDERLYPOPUTION_DETAIL,DISABLEPOPUTION_DETAIL,DBPOPUTION_DETAIL,WBPOPULATION_DETAIL,DBBYPOPUTION_DETAIL
    }
}
